<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Plantilla\Module'                        => __DIR__ . '/Module.php',
    'Plantilla\Controller\IndexController' => __DIR__ . '/src/Plantilla/Controller/IndexController.php',
    'Plantilla\Framework\TestCase'        => __DIR__ . '/tests/Plantilla/Framework/TestCase.php',
    'Plantilla\SampleTest'                => __DIR__ . '/tests/Plantilla/SampleTest.php',
);